version: '3.5'

services:
    mooc-2.3-back:
      image: test-back
      ports:
        - 8000:8000
      volumes:
        - /home/warhol/mooc/2.3/logs.txt:/usr/local/www/backend/logs.txt

    mooc-2.3-front:
      image: test-front
      ports:
        - 5000:5000
